-- MySQL Script generated by MySQL Workbench
-- Sat Feb 27 01:40:38 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Countries
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Countries
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Countries` DEFAULT CHARACTER SET utf8 ;
USE `Countries` ;

-- -----------------------------------------------------
-- Table `Countries`.`Countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Countries`.`Countries` (
  `idCountry` INT NOT NULL,
  `Country` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCountry`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Countries`.`Regions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Countries`.`Regions` (
  `idRegions` INT NULL,
  `Region` VARCHAR(45) NULL,
  `Countries_idCountry` INT NOT NULL,
  PRIMARY KEY (`idRegions`),
  INDEX `fk_Regions_Countries_idx` (`Countries_idCountry` ASC) VISIBLE,
  CONSTRAINT `fk_Regions_Countries`
    FOREIGN KEY (`Countries_idCountry`)
    REFERENCES `Countries`.`Countries` (`idCountry`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Countries`.`Rayons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Countries`.`Rayons` (
  `idRayons` INT NOT NULL,
  `Rayon` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRayons`),
  CONSTRAINT `idRayons`
    FOREIGN KEY (`idRayons`)
    REFERENCES `Countries`.`Regions` (`idRegions`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Countries`.`Cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Countries`.`Cities` (
  `idCities` INT NOT NULL,
  `City` VARCHAR(45) NOT NULL,
  `Regions_idRegions` INT NOT NULL,
  `Rayons_idRayons` INT NOT NULL,
  PRIMARY KEY (`idCities`, `Rayons_idRayons`),
  INDEX `fk_Cities_Regions1_idx` (`Regions_idRegions` ASC) VISIBLE,
  INDEX `fk_Cities_Rayons1_idx` (`Rayons_idRayons` ASC) VISIBLE,
  CONSTRAINT `fk_Cities_Regions1`
    FOREIGN KEY (`Regions_idRegions`)
    REFERENCES `Countries`.`Regions` (`idRegions`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cities_Rayons1`
    FOREIGN KEY (`Rayons_idRayons`)
    REFERENCES `Countries`.`Rayons` (`idRayons`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
